%% Import data from text file.
% Script for importing data from the following text file:
%
%    /Volumes/Backup/OneDrive/OneDrive - University of Edinburgh/Google Drive/Edinburgh/Year 4/BEng Project/Data/EVChargeData.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2018/01/29 13:32:06

%% Initialize variables.
filename = '/Volumes/Backup/OneDrive/OneDrive - University of Edinburgh/Google Drive/Edinburgh/Year 4/BEng Project/Data/';
filename = strcat(filename,Datafile);
delimiter = ',';
startRow = 2;

%% Format for each line of text:
%   column1: text (%s)
%	column2: datetimes (%{yyyy-MM-dd HH:mm}D)
%   column3: datetimes (%{yyyy-MM-dd HH:mm}D)
%	column4: double (%f)
%   column5: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%{yyyy-MM-dd HH:mm}D%{yyyy-MM-dd HH:mm}D%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r','n','UTF-8');
% Skip the BOM (Byte Order Mark).
fseek(fileID, 3, 'bof');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'TextType', 'string', 'EmptyValue', NaN, 'HeaderLines' ,startRow-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
% EVChargeData = table(dataArray{1:end-1}, 'VariableNames', {'ParticipantID','BatteryChargeStartDate','BatteryChargeStopDate','StartingSoCof12','EndingSoCof12'});
EVChargeData = dataArray;
% For code requiring serial dates (datenum) instead of datetime, uncomment
% the following line(s) below to return the imported dates as datenum(s).

% EVChargeData.BatteryChargeStartDate=datenum(EVChargeData.BatteryChargeStartDate);EVChargeData.BatteryChargeStopDate=datenum(EVChargeData.BatteryChargeStopDate);

%% Clear temporary variables
clearvars filename delimiter startRow formatSpec fileID dataArray ans;